; pokemon's overworld sprites
const_value = 0

	const SPRITE_MON              ; $0
	const SPRITE_BALL_M           ; $1
	const SPRITE_HELIX            ; $2
	const SPRITE_FAIRY            ; $3
	const SPRITE_BIRD_M           ; $4
	const SPRITE_WATER            ; $5
	const SPRITE_BUG              ; $6
	const SPRITE_GRASS            ; $7
	const SPRITE_SNAKE            ; $8
	const SPRITE_QUADRUPED        ; $9
	const SPRITE_PIKACHU_FAMILY   ; $A
; overworld sprites
const_value = 1

	const SPRITE_RED                       ; $01
	const SPRITE_BLUE                      ; $02
	const SPRITE_OAK                       ; $03
	const SPRITE_BUG_CATCHER               ; $04
	const SPRITE_SLOWBRO                   ; $05
	const SPRITE_LASS                      ; $06
	const SPRITE_BLACK_HAIR_BOY_1          ; $07
	const SPRITE_LITTLE_GIRL               ; $08
	const SPRITE_BIRD                      ; $09
	const SPRITE_FAT_BALD_GUY              ; $0a
	const SPRITE_GAMBLER                   ; $0b
	const SPRITE_BLACK_HAIR_BOY_2          ; $0c
	const SPRITE_GIRL                      ; $0d
	const SPRITE_HIKER                     ; $0e
	const SPRITE_FOULARD_WOMAN             ; $0f
	const SPRITE_GENTLEMAN                 ; $10
	const SPRITE_DAISY                     ; $11
	const SPRITE_BIKER                     ; $12
	const SPRITE_SAILOR                    ; $13
	const SPRITE_COOK                      ; $14
	const SPRITE_BIKE_SHOP_GUY             ; $15
	const SPRITE_MR_FUJI                   ; $16
	const SPRITE_GIOVANNI                  ; $17
	const SPRITE_ROCKET                    ; $18
	const SPRITE_MEDIUM                    ; $19
	const SPRITE_WAITER                    ; $1a
	const SPRITE_ERIKA                     ; $1b
	const SPRITE_MOM_GEISHA                ; $1c
	const SPRITE_BRUNETTE_GIRL             ; $1d
	const SPRITE_LANCE                     ; $1e
	const SPRITE_UNUSED_1                  ; $1f
	const SPRITE_OAK_AIDE                  ; $20
	const SPRITE_ROCKER                    ; $21
	const SPRITE_SWIMMER                   ; $22
	const SPRITE_WHITE_PLAYER              ; $23
	const SPRITE_GYM_HELPER                ; $24
	const SPRITE_OLD_PERSON                ; $25
	const SPRITE_MART_GUY                  ; $26
	const SPRITE_FISHER                    ; $27
	const SPRITE_OLD_MEDIUM_WOMAN          ; $28
	const SPRITE_NURSE                     ; $29
	const SPRITE_CABLE_CLUB_WOMAN          ; $2a
	const SPRITE_MR_MASTERBALL             ; $2b
	const SPRITE_LAPRAS_GIVER              ; $2c
	const SPRITE_WARDEN                    ; $2d
	const SPRITE_SS_CAPTAIN                ; $2e
	const SPRITE_FISHER2                   ; $2f
	const SPRITE_BLACKBELT                 ; $30
	const SPRITE_GUARD                     ; $31
	const SPRITE_UNUSED_2                  ; $32
	const SPRITE_MOM                       ; $33
	const SPRITE_BALDING_GUY               ; $34
	const SPRITE_YOUNG_BOY                 ; $35
	const SPRITE_UNUSED_3                  ; $36
	const SPRITE_GAMEBOY_KID               ; $37
	const SPRITE_CLEFAIRY                  ; $38
	const SPRITE_AGATHA                    ; $39
	const SPRITE_BRUNO                     ; $3a
	const SPRITE_LORELEI                   ; $3b
	const SPRITE_SEEL                      ; $3c
	const SPRITE_PIKACHU                   ; $3d
	const SPRITE_OFFICER_JENNY             ; $3e
	const SPRITE_SANDSHREW                 ; $3f
	const SPRITE_ODDISH                    ; $40
	const SPRITE_BULBASAUR                 ; $41
	const SPRITE_JIGGLYPUFF                ; $42
	const SPRITE_CLEFAIRY_2                ; $43
	const SPRITE_CHANSEY                   ; $44
	const SPRITE_JESSIE                    ; $45
	const SPRITE_JAMES                     ; $46

	; 4-tile sprites
	const SPRITE_BALL                      ; $47
	const SPRITE_OMANYTE                   ; $48
	const SPRITE_BOULDER                   ; $49
	const SPRITE_PAPER_SHEET               ; $4a
	const SPRITE_BOOK_MAP_DEX              ; $4b
	const SPRITE_CLIPBOARD                 ; $4c
	const SPRITE_SNORLAX                   ; $4d
	const SPRITE_OLD_AMBER_COPY            ; $4e
	const SPRITE_OLD_AMBER                 ; $4f
	const SPRITE_LYING_OLD_MAN_UNUSED_1    ; $50
	const SPRITE_LYING_OLD_MAN_UNUSED_2    ; $51
	const SPRITE_LYING_OLD_MAN             ; $52
	const SPRITE_PARTY_LEADER              ; $53
; pokemon's follow sprites
const_value = 2

	const SPRITE_F_BULBASAUR  ; 1
	const SPRITE_F_IVYSAUR    ; 2
	const SPRITE_F_VENUSAUR   ; 3
	const SPRITE_F_CHARMANDER ; 4
	const SPRITE_F_CHARMELEON ; 5
	const SPRITE_F_CHARIZARD  ; 6
	const SPRITE_F_SQUIRTLE   ; 7
	const SPRITE_F_WARTORTLE  ; 8
	const SPRITE_F_BLASTOISE  ; 9
	const SPRITE_F_CATERPIE   ; 10
	const SPRITE_F_METAPOD    ; 11
	const SPRITE_F_BUTTERFREE ; 12
	const SPRITE_F_WEEDLE     ; 13
	const SPRITE_F_KAKUNA     ; 14
	const SPRITE_F_BEEDRILL   ; 15
	const SPRITE_F_PIDGEY     ; 16
	const SPRITE_F_PIDGEOTTO  ; 17
	const SPRITE_F_PIDGEOT    ; 18
	const SPRITE_F_RATTATA    ; 19
	const SPRITE_F_RATICATE   ; 20
	const SPRITE_F_SPEAROW    ; 21
	const SPRITE_F_FEAROW     ; 22
	const SPRITE_F_EKANS      ; 23
	const SPRITE_F_ARBOK      ; 24
	const SPRITE_F_PIKACHU    ; 25
	const SPRITE_F_RAICHU     ; 26
	const SPRITE_F_SANDSHREW  ; 27
	const SPRITE_F_SANDSLASH  ; 28
	const SPRITE_F_NIDORAN_F  ; 29
	const SPRITE_F_NIDORINA   ; 30
	const SPRITE_F_NIDOQUEEN  ; 31
	const SPRITE_F_NIDORAN_M  ; 32
	const SPRITE_F_NIDORINO   ; 33
	const SPRITE_F_NIDOKING   ; 34
	const SPRITE_F_CLEFAIRY   ; 35
	const SPRITE_F_CLEFABLE   ; 36
	const SPRITE_F_VULPIX     ; 37
	const SPRITE_F_NINETALES  ; 38
	const SPRITE_F_JIGGLYPUFF ; 39
	const SPRITE_F_WIGGLYTUFF ; 40
	const SPRITE_F_ZUBAT      ; 41
	const SPRITE_F_GOLBAT     ; 42
	const SPRITE_F_ODDISH     ; 43
	const SPRITE_F_GLOOM      ; 44
	const SPRITE_F_VILEPLUME  ; 45
	const SPRITE_F_PARAS      ; 46
	const SPRITE_F_PARASECT   ; 47
	const SPRITE_F_VENONAT    ; 48
	const SPRITE_F_VENOMOTH   ; 49
	const SPRITE_F_DIGLETT    ; 50
	const SPRITE_F_DUGTRIO    ; 51
	const SPRITE_F_MEOWTH     ; 52
	const SPRITE_F_PERSIAN    ; 53
	const SPRITE_F_PSYDUCK    ; 54
	const SPRITE_F_GOLDUCK    ; 55
	const SPRITE_F_MANKEY     ; 56
	const SPRITE_F_PRIMEAPE   ; 57
	const SPRITE_F_GROWLITHE  ; 58
	const SPRITE_F_ARCANINE   ; 59
	const SPRITE_F_POLIWAG    ; 60
	const SPRITE_F_POLIWHIRL  ; 61
	const SPRITE_F_POLIWRATH  ; 62
	const SPRITE_F_ABRA       ; 63
	const SPRITE_F_KADABRA    ; 64
	const SPRITE_F_ALAKAZAM   ; 65
	const SPRITE_F_MACHOP     ; 66
	const SPRITE_F_MACHOKE    ; 67
	const SPRITE_F_MACHAMP    ; 68
	const SPRITE_F_BELLSPROUT ; 69
	const SPRITE_F_WEEPINBELL ; 70
	const SPRITE_F_VICTREEBEL ; 71
	const SPRITE_F_TENTACOOL  ; 72
	const SPRITE_F_TENTACRUEL ; 73
	const SPRITE_F_GEODUDE    ; 74
	const SPRITE_F_GRAVELER   ; 75
	const SPRITE_F_GOLEM      ; 76
	const SPRITE_F_PONYTA     ; 77
	const SPRITE_F_RAPIDASH   ; 78
	const SPRITE_F_SLOWPOKE   ; 79
	const SPRITE_F_SLOWBRO    ; 80
	const SPRITE_F_MAGNEMITE  ; 81
	const SPRITE_F_MAGNETON   ; 82
	const SPRITE_F_FARFETCHD  ; 83
	const SPRITE_F_DODUO      ; 84
	const SPRITE_F_DODRIO     ; 85
	const SPRITE_F_SEEL       ; 86
	const SPRITE_F_DEWGONG    ; 87
	const SPRITE_F_GRIMER     ; 88
	const SPRITE_F_MUK        ; 89
	const SPRITE_F_SHELLDER   ; 90
	const SPRITE_F_CLOYSTER   ; 91
	const SPRITE_F_GASTLY     ; 92
	const SPRITE_F_HAUNTER    ; 93
	const SPRITE_F_GENGAR     ; 94
	const SPRITE_F_ONIX       ; 95
	const SPRITE_F_DROWZEE    ; 96
	const SPRITE_F_HYPNO      ; 97
	const SPRITE_F_KRABBY     ; 98
	const SPRITE_F_KINGLER    ; 99
	const SPRITE_F_VOLTORB    ; 100
	const SPRITE_F_ELECTRODE  ; 101
	const SPRITE_F_EXEGGCUTE  ; 102
	const SPRITE_F_EXEGGUTOR  ; 103
	const SPRITE_F_CUBONE     ; 104
	const SPRITE_F_MAROWAK    ; 105
	const SPRITE_F_HITMONLEE  ; 106
	const SPRITE_F_HITMONCHAN ; 107
	const SPRITE_F_LICKITUNG  ; 108
	const SPRITE_F_KOFFING    ; 109
	const SPRITE_F_WEEZING    ; 110
	const SPRITE_F_RHYHORN    ; 111
	const SPRITE_F_RHYDON     ; 112
	const SPRITE_F_CHANSEY    ; 113
	const SPRITE_F_TANGELA    ; 114
	const SPRITE_F_KANGASKHAN ; 115
	const SPRITE_F_HORSEA     ; 116
	const SPRITE_F_SEADRA     ; 117
	const SPRITE_F_GOLDEEN    ; 118
	const SPRITE_F_SEAKING    ; 119
	const SPRITE_F_STARYU     ; 120
	const SPRITE_F_STARMIE    ; 121
	const SPRITE_F_MR_MIME    ; 122
	const SPRITE_F_SCYTHER    ; 123
	const SPRITE_F_JYNX       ; 124
	const SPRITE_F_ELECTABUZZ ; 125
	const SPRITE_F_MAGMAR     ; 126
	const SPRITE_F_PINSIR     ; 127
	const SPRITE_F_TAUROS     ; 128
	const SPRITE_F_MAGIKARP   ; 129
	const SPRITE_F_GYARADOS   ; 130
	const SPRITE_F_LAPRAS     ; 131
	const SPRITE_F_DITTO      ; 132
	const SPRITE_F_EEVEE      ; 133
	const SPRITE_F_VAPOREON   ; 134
	const SPRITE_F_JOLTEON    ; 135
	const SPRITE_F_FLAREON    ; 136
	const SPRITE_F_PORYGON    ; 137
	const SPRITE_F_OMANYTE    ; 138
	const SPRITE_F_OMASTAR    ; 139
	const SPRITE_F_KABUTO     ; 140
	const SPRITE_F_KABUTOPS   ; 141
	const SPRITE_F_AERODACTYL ; 142
	const SPRITE_F_SNORLAX    ; 143
	const SPRITE_F_ARTICUNO   ; 144
	const SPRITE_F_ZAPDOS     ; 145
	const SPRITE_F_MOLTRES    ; 146
	const SPRITE_F_DRATINI    ; 147
	const SPRITE_F_DRAGONAIR  ; 148
	const SPRITE_F_DRAGONITE  ; 149
	const SPRITE_F_MEWTWO     ; 150
	const SPRITE_F_MEW        ; 151
	const SPRITE_F_CHIKORITA  ; 151

; player types
const_value = 3
	const SPRITE_P_RED        ; 00
	const SPRITE_P_BLUE       ; 01

; different kinds of people events
ITEM    EQU $80
TRAINER EQU $40

BOULDER_MOVEMENT_BYTE_2 EQU $10

; sprite facing directions
SPRITE_FACING_DOWN  EQU $00
SPRITE_FACING_UP    EQU $04
SPRITE_FACING_LEFT  EQU $08
SPRITE_FACING_RIGHT EQU $0C
